
VERSION=1.2a

dist: 
	mkdir -p thc-rfs-client-${VERSION}
	cp -a ../man ../thc-rfs thc-rfs-client-${VERSION}/
	tar cfz thc-rfs-client-${VERSION}.tar.gz thc-rfs-client-${VERSION}
	rm -rf thc-rfs-client-${VERSION}/
	ls -al thc-rfs-client-${VERSION}.tar.gz

